image: hpiswa/smalltalkci

variables:
  COVERAGE_DIR: /builds/PharoProject/coverage

stages:
  - test
  - coverage

run tests:
  stage: test
  script: smalltalkci -s "Pharo64-11.0"
  artifacts:
    paths:
      - $COVERAGE_DIR

extract coverage:
  stage: coverage
  image: python:3.9-slim-buster
  script:
    - pip install lcov-cobertura-fix==1.6.1a2
    - lcov_cobertura $COVERAGE_DIR/lcov.info --output $COVERAGE_DIR/coverage.xml
  dependencies: 
    - run tests